/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * save, and this file will regenerate automatically.
 */

export interface Event {
  _id: string
  published: boolean
  title: string
  slug: string
  description: string
  logo?: string
  backgroundImage?: string
  location: {
    address1: string
    address2: string
    city: string
    postalCode: string
    province: string
    country: string
  }
  startDate: string
  endDate: string
  attendanceForm: {
    rank: boolean
    firstName: boolean
    lastName: boolean
    assignment: boolean
    assignmentDetails?: boolean
    delegations: boolean
    delegationsDetails: {
      name: string
      value: string
    }[]
    phone: boolean
    whatsapp: boolean
    institutionalEmail: boolean
    spouseCheckbox: boolean
    spouseFirstName: boolean
    spouseLastName: boolean
    allergies: boolean
    placeOfArrival: boolean
    dateOfArrival: boolean
    timeOfArrival: boolean
    arrivalTransportId: boolean
    placeOfDeparture: boolean
    dateOfDeparture: boolean
    timeOfDeparture: boolean
    departureTransportId: boolean
    remarks: boolean
  }
}
